### ISSUE TITLE
Proposal: Data retention time limit

### ISSUE THREAD

**Issue by auggod** [offen/offen#681]
After some time, offen gets unusable because there's too much data.
It takes forever to fetch/aggregate data or it just fails. Offen is also suck with the spinning logo.
Unless we can fix this perf issue, I think we should be able to delete the older data.

**Comment by m90** [comment]
This doesn't sound pretty. Would you mind disclosing the approximate number of unique users / sessions for such a view that is failing / too slow to be usable? Is this across the entire 6 months or does it happen earlier already? Also, when you say it fails from time to time, do you get an error message of some sort, either on screen or in the browser console? What's the browser you are using? Thanks.

**Comment by m90** [comment]
Also, just to be sure: are you running a version equal or later than v0.2.0?

**Comment by m90** [comment]
Oh, also: do you use some sort of "private mode" that could cause your browser to regularly flush your IndexedDB?

**Comment by auggod** [comment]
I'm running latest version, it's a problem since the first time I tried offen.
I just tried on linux/brave (first connection using the browser) and it just failed to fetch the data and the container hosting offen just crashed.
On macos/brave, I also got the 'aw snap' error.

We have thousands of pageviews daily and at peeks 1000-3000 unique visitors.
I think, after a month it gets unusable.

**Comment by auggod** [comment]
I see 120000 events entries into the indexed db

**Comment by m90** [comment]
Thanks for the extra info.

I think there's two aspects to this:
1. when you have as much data as you do, a new sync will try to load all of it and the computer chokes because it's just too much. This is bad technical design on our end, but it should definitely be possible to improve this by paginating these initial calls and do the initial aggregation in more digestable pieces. This won't make it faster, but at least it shouldn't crash anymore. I'll see if I can get this implemented soonish and included in the next release.
2. I'm not entirely sure if your browser actually keeps the aggregates around or will delete them after your session ends (your comment about how you've always had this makes me think so a little). On the high(er) traffic sites (not as much as you are seeing though) that I run Offen on, things got decently usable ever since v0.2.0 introduced aggregates. This of course, requires your browser to keep these around across sessions (they are encrypted locally, so that's ok). I'll need to install Brave myself to see what it does here. Considering it's privacy focused I could imagine it's very eager when it comes to deleting data.

**Comment by auggod** [comment]
I tried on a brave browser (different computer) where I didn't use offen before and the data failed to load.

**Comment by m90** [comment]
I'll dig into this deeper on the weekend. Thanks for the input.

As for your original proposal: you are envisioning setting sth like `OFFEN_RETENTION_DAYS=30` and then data gets deleted way earlier than by default? (ironically this existed once but got removed as we thought the 6 months would be a good value for everyone https://github.com/offen/offen/commit/fb4e31b26f57b9162ff33eac893b9f453ec30a5c)

**Comment by auggod** [comment]
I don't feel like I need more than a week retention. I don't check offen very offen, only sometimes because I know there's going to be a surge in activity. We have other ways to track activity with Resonate, mainly play counts.

**Comment by m90** [comment]
So we're looking into this right now and thought the best approach to making retention configurable is to map allowed configurations to the existing UI in order to ensure that users also understand how long their data is retained (instead of seeing a lot of expected data missing in a 6 months view for example).

This would mean we allow the following values:

- 6 months (default)
- 12 weeks
- 6 weeks
- 30 days
- 7 days

Do you think that would be flexible enough for your use case?

---

As for the performance issues I could reproduce the crash issue with a very high number of users (using random data) and could also prevent the crashing by throttling concurrency. This however makes it even slower. I think I will work on this in a separate branch / task then and focus on the retention first.

**Comment by m90** [comment]
Configuring retention is now possible as of [`v1.0.0`](https://github.com/offen/offen/releases), docs can be found here: https://docs.offen.dev/running-offen/configuring-the-application/#offen_app_retention
